### PR TITLE
Placement configuration param

### PR DESCRIPTION
**Pull request by isuftin**
Add ability to define the "placement" parameter for a JupyterHub notebook service from jupyterhub_config.py configuration

### CODE REVIEW

**Comment by isuftin** [comment]
Touches on https://github.com/cassinyio/SwarmSpawner/issues/17

**Comment by hans-permana** [comment]
this PR would help me too :)

**Comment by isuftin** [comment]
@hans-permana I'll take a second look at this and amend my PR.

**Comment by hans-permana** [comment]
just need to reformat the indentation to make Travis happy.

**Pull request merged**
